<?php

namespace AppBundle\Repository;

/**
 * LinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinksRepository extends \Doctrine\ORM\EntityRepository
{
}
